#!/usr/bin/php
<?php
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING. If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/refresh_ao
 *  version: 1.3
 *  coder: Simone De Gregori
 *
 */
// initialisation
// report errors by setting display_errors to true (=1)
ini_set('display_errors', '1');
// report all PHP errors: set error_reporting to -1
ini_set('error_reporting', -1);
// set the name of the error log file
ini_set('error_log', '/var/log/runeaudio/refresh_ao.log');
// common include
require_once('/srv/http/app/libs/runeaudio.php');
require_once('/srv/http/app/libs/openredis.php');
// reset logfile
sysCmd('echo "--------------- start: refresh_ao ---------------" > /var/log/runeaudio/refresh_ao.log');
// logging starting message
runelog('WORKER refresh_ao STARTING...');
// define APP global
define('APP', '/srv/http/app/');

// get the lock status
$lock = $redis->get('lock_refresh_ao');
runelog('lock status ', $lock);
// refesh audio hardware status (soundcards and MPD config)
if (($lock === '0') || ($lock === '9')  || ($lock >= 9)) {
    // set the lock
    $redis->set('lock_refresh_ao', '1');
    // wake up any hdmi interfaces
    sysCmd('export DISPLAY=:0 ; xrandr');
    // force alsa to reload all card profiles (should not be required, but some USB audio devices seem to need it)
    sysCmd('alsactl kill rescan');
    wrk_mpdconf($redis, 'refreshsoundcards');
    ui_notify('Audio Output', 'configuration changed.');
    // unlock
    $redis->set('lock_refresh_ao', '0');
} else {
    echo "LOCKED!\n";
    // just in case something goes wrong increment the lock value by 1
    // when it reaches 9 (this should never happen) it will be processed as if there is no lock
    $lock += 1;
    $redis->set('lock_refresh_ao', $lock);
}
runelog('lock status ', $redis->get('lock_refresh_ao'));
// close Redis connection
$redis->close();

runelog('WORKER refresh_ao END...');
