#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING.  If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
#
#  file: command/rune_shutdown
#  version: 1.3
#  coder: Simone De Gregori
#

# continue on errors
set +e
echo "rune_shutdown started"
#
echo "Stop MPD, services and unmount shares..."
# stop the player
mpc stop
sleep 1
# stop MPD
mpd --kill
sleep 1
# stop mpd related jobs
systemctl stop ashuffle upmpdcli mpdscribble mpd
# stop webserver, php & local browser
systemctl stop nginx local-browser
# display the splash screen if applicable (local-browser must be stopped first)
enablesplash=$( redis-cli hget local_browser enable-splash )
if [[ "$enablesplash" != "0" ]] ; then
    if [[ $1 == "poweroff" ]] ; then
        echo "power off RuneAudio"
        splash="/usr/share/bootsplash/shutdown.png"
    else
        echo "reboot RuneAudio"
        splash="/usr/share/bootsplash/reboot.png"
    fi
    ply-image "$splash"
fi
# reset any lock's
locks=$( redis-cli --scan --pattern lock_* | sort -u )
for lock in $locks ; do
    redis-cli set "$lock" 0
done
# force redis to save all its variables to disk
redis-cli save
# stop most of the systemd units which can be stopped
systemctl stop spotifyd shairport-sync spopd smbd smb nmbd nmb rune_PL_wrk rune_SSM_wrk
# unmount the local and network storage devices
umount -Rf /mnt/MPD/NAS/*
umount -Rf /mnt/MPD/USB/*
rmdir /mnt/MPD/NAS/*
rmdir /mnt/MPD/USB/*
# udevil mount points have a file in them which causes the previous line to fail, the line below cleans them up
udevil clean
# blank the local browser screen
export DISPLAY=:0
xset dpms force off
# echo a message to clear any error status which could have been generated
echo "rune_shutdown finished"
