#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING. If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
#
#  file: command/rune_prio
#  version: 1.3
#  coder: Simone De Gregori
#
#####################################
set +e # continue on errors
prio_nice () {
# MPD has the capability of setting its own priority in real time
# the following is to make sure that its associated processes are also set to a higher priority
for pid in $(pgrep -w mpd);
do
    renice -1 $pid;
done;
renice -1 $(ps -Teo spid,pid,ni,pri,fname | grep -i 'mpd' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
renice -1 $(pgrep -w mpd)
renice -1 $(pgrep -w shairport-sync)
renice -1 $(pgrep -w spopd)
renice -1 $(pgrep -w upmpdcli)
# set the local browser to a low value
for pid in $(pgrep -w chromium);
do
    renice 10 $pid;
done;
renice 10 $(ps -Teo spid,pid,ni,pri,fname | grep -i 'chromium' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
renice 10 $(pgrep -w chromium)
renice 3 $(pgrep -w ashuffle)
renice 3 $(pgrep -w local-browser)
renice 3 $(pgrep -w mpdscribble)
renice 2 $(pgrep -w nmbd)
renice 2 $(pgrep -w nmb)
renice 3 $(pgrep -w rune_PL_wrk)
renice 3 $(pgrep -w rune_SSM_wrk)
renice 3 $(pgrep -w rune_SY_wrk)
renice 2 $(pgrep -w smbd)
renice 2 $(pgrep -w smb)
renice 2 $(pgrep -w sshd)
renice 2 $(pgrep -w xinit)
renice 1 $(pgrep -w Xorg)
renice 1 $(pgrep -w matchbox-window)
renice 2 $(pgrep -w xbindkeys)
renice 4 $(pgrep -w uwsgi)
renice 6 $(pgrep -w upowerd)
}

prio_default () {
# always leave chromium at a lower priority
# always leave upowerd at a lower priority
# always leave uwsgi at a lower priority
for pid in $(pgrep -w mpd);
do
    renice 0 $pid;
done;
renice 0 $(pgrep -w mpd)
renice 0 $(pgrep -w shairport-sync)
renice 0 $(pgrep -w spopd)
renice 0 $(pgrep -w upmpdcli)
renice 0 $(pgrep -w ashuffle)
renice 0 $(pgrep -w local-browser)
renice 0 $(pgrep -w mpdscribble)
renice 0 $(pgrep -w nmbd)
renice 0 $(pgrep -w nmb)
renice 0 $(pgrep -w rune_PL_wrk)
renice 0 $(pgrep -w rune_SSM_wrk)
renice 0 $(pgrep -w rune_SY_wrk)
renice 0 $(pgrep -w smbd)
renice 0 $(pgrep -w smb)
renice 0 $(pgrep -w sshd)
renice 0 $(pgrep -w xinit)
renice 0 $(pgrep -w Xorg)
renice 0 $(pgrep -w matchbox-window)
renice 0 $(pgrep -w xbindkeys)
}

if [ "$1" == "default" ]; then
    echo "set default priority settings"
    prio_default
    exit 0
fi

if [ "$1" == "nice" ]; then
    echo "set nice priority settings"
    prio_nice
    exit 0
fi

echo "RuneAudio process priority settings"
echo "Usage: $0 {default|nice}"
exit 1
