#!/usr/bin/php
<?php
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/ui_update_async {usec_delay}
 *  version: 1.3
 *  coder: Simone De Gregori
 *
 */
 // initialisation
// report errors: set display_errors to true (=1)
ini_set('display_errors', '1');
// report all PHP errors: set error_reporting to -1
ini_set('error_reporting', -1);
// set the name of the error log file
ini_set('error_log', '/var/log/runeaudio/ui_update_async.log');
// common include
require_once('/srv/http/app/libs/runeaudio.php');
// // Connect to Redis backend
// require_once('/srv/http/app/libs/openredis.php');
// reset logfile
sysCmd('echo "--------------- start: ui_update_async ---------------" > /var/log/runeaudio/ui_update_async.log');
// logging starting message
runelog('WORKER ui_update_async STARTING...');
// define APP global
define('APP', '/srv/http/app/');

// delay for the number of microseconds given in the 1st parameter (default is 500000 - this is 0.5 seconds)
if (isset($argv[1]) && is_numeric($argv[1])) {
    if ($argv[1] > 0) {
        usleep($argv[1]);
    }
} else {
    usleep(500000);
}
// ui_update($redis, $sock, $clientUUID=null)
sysCmd('curl -s -X GET http://localhost/command/?cmd=renderui');

runelog('WORKER ui_update_async END...');

