#!/usr/bin/php
<?php
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/usbmount
 *  version: 1.3
 *  coder: Simone De Gregori
 *
 */
// common include
ini_set('display_errors', '1');
ini_set('error_reporting', -1);
ini_set('error_log','/var/log/runeaudio/usbmount.log');
// RuneAudio Library include
require_once('/srv/http/app/libs/runeaudio.php');
// Connect to Redis backend include
require_once('/srv/http/app/libs/openredis.php');
// handle HFS+ mount
if (strpos(file_get_contents('/proc/mounts'), '/mnt/MPD/USB/EFI vfat')) {
    sysCmd('devmon --unmount /mnt/MPD/USB/EFI');
}
// record mount point info in Redis
$redis->Del('usbmounts');
// $usbmounts = sysCmd("df -h | grep USB | cut -d ' ' -f 1,23,31,32 | cut -d '/' -f 3,6-7");
$usbmounts = sysCmd("df -hl | grep '/mnt/MPD/USB'");
foreach ($usbmounts as $line) {
    $line = array_values(array_filter(explode(' ', trim($line))));
    // fix any spaces in volume name
    for ($cnt = 6; isset($line[$cnt]); $cnt++) {
        if (!empty($line[$cnt])) {
            $line[5] .= " ".$line[$cnt];
        }
        // should not be needed, but break at cnt 16 just in case, this is 10 spaces
        if ($cnt = 16 ) {
            break;
        }
    }
    // debug
    // print_r($line);
    $redis->hSet('usbmounts', $line[0], json_encode(array('device' => $line[0], 'size' => $line[1], 'use' => $line[4], 'name' => substr(trim($line[5]), 9))));
    // debug
    runelog('usbmount line: ', $line);
}
// set file protection and ownership of USB mounts
sysCmd('chown mpd.audio /mnt/MPD/USB');
sysCmd('chown mpd.audio /mnt/MPD/USB/*');
sysCmd('chmod 777 /mnt/MPD/USB');
sysCmd('chmod 777 /mnt/MPD/USB/*');
// remove 'ghost' usb mounts
// use udevil clean to remove any ghost entries
sysCmd('udevil clean');
// check if usb autorebuild is set
if ($redis->get('usb_db_autorebuild')) {
    // update MPD database
    $retval = sysCmd('mpc update USB');
    if (isset($retval) && is_array($retval) && strpos(' '.$retval[0], 'error')) {
        // mpc has returned an error, mpd is probably starting up
        //  set redis variable 'usb_db_autorebuild_retry' which will be acted on by rune_SY_wrk
        $redis->set('usb_db_autorebuild_retry', 1);
    }
}
// update library panel to display the new mount
ui_libraryHome($redis);
// restart Samba in order to pick up the new USB mount
wrk_restartSamba($redis);
// close Redis connection
$redis->close();
