d /run/owntone/music 0755 owntone audio -
d /var/cache/owntone 0755 owntone audio -
d /var/lib/owntone 0755 owntone audio -
d /var/run/owntone/.config 0755 owntone audio -
L+ /etc/sysusers.d/owntone.conf - - - - /dev/null
f /var/log/runeaudio/owntone.log 0666 owntone audio -
p /run/owntone/music/pipe_mpd.fifo 666 owntone audio -
p /run/owntone/music/pipe_mpd.fifo.metadata 666 owntone audio -
p /run/owntone/music/pipe_sc.fifo 666 owntone audio -
p /run/owntone/music/pipe_sc.fifo.metadata 666 owntone audio -
p /run/owntone/music/pipe_ap.fifo 666 owntone audio -
p /run/owntone/music/pipe_ap.fifo.metadata 666 owntone audio -
p /run/owntone/music/pipe_bt.fifo 666 owntone audio -
p /run/owntone/music/pipe_bt.fifo.metadata 666 owntone audio -
