[uwsgi]
# App working directory
chdir = /srv/http/amixer
# WSGI module (your Flask/Django entry point)
module = wsgi:application
# Master process + worker processes
master = true
processes = 2
# Socket: place it inside systemd StateDirectory for the instance
socket = /run/uwsgi/amixer-webui/amixer.sock
chmod-socket = 660
#uid = www-amixer-webui
#gid = www-data
# Cleanup the socket on exit
vacuum = true
# Stop all processes gracefully when systemd stops the service
die-on-term = true
# Optional: enable uWSGI logging (stderr -> journal)
logto = /var/log/runeaudio/uwsgi.log
plugin = python3
