# DHCP-Server for WIFI-Interface
interface=ap0
# exclude DHCP-Server for ethernet
no-dhcp-interface=eth0
no-dhcp-interface=wlan0
# IPv4 address-range and lease-time
dhcp-range=192.168.5.2,192.168.5.254,24h
# DNS
dhcp-option=option:dns-server,192.168.5.1
# set port to 5300
port=5300
# for systemd-resolved, we need this
resolv-file=/run/systemd/resolve/resolv.conf
