#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING. If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
#
#  file: app/default/config/etc/NetworkManager/dsipatch.d/dnssec_fix
#  version: 0.7
#  coder: gearhead
#  date: February 2026
#
# The RPi doe snot have a real time clock and at bootup, the time may not be close enough to sync
# When systemd-resolved is running with DNSSEC switched on the nts time servers will return an invalid
# response when the certificate is checked and therefore not be available to sync time
# at boot because time is incorrect. The incorrect time prevents systemd-resolved resoving the NTS URL's
#
# The workaround is to let NetworkManager run a script as an interface comes up to check if DNSSEC is
# switched (globally) on and if so, switch it off until a timesync has taken place to then switch DNSSEC on
# for each link.
#
# DNSSEC will only be enabled when the redis variable network_dnssec has a value of 1
#

#!/bin/bash
# Handle DNSSEC on devices without RTC (e.g. Raspberry Pi)
# When DNSSEC is enabled, temporarily disable it until time is synced
# then re-enable it to ensure valid DNSSEC validation

if [ "$2" = "up" ]; then
    # Get the global DNSSEC setting
    global_dnssec=$(/usr/bin/resolvectl status | grep "^Global$" -A 10 | grep "DNSSEC=" | head -1)
    global_mode=$(echo "$global_dnssec" | grep -o "DNSSEC=[^ ]*" | cut -d'=' -f2 | cut -d'/' -f1)

    # Only act if DNSSEC is enabled and time is not yet synced
    if [ "$global_mode" = "yes" ] || [ "$global_mode" = "allow-downgrade" ]; then
        if ! timedatectl status | grep -q "System clock synchronized: yes"; then
            # Temporarily disable DNSSEC on this link
            /usr/bin/resolvectl dnssec "$1" no 2>/dev/null

            # Background: wait for time sync then re-enable
            (
                timeout=60
                while [ $timeout -gt 0 ]; do
                    if timedatectl status | grep -q "System clock synchronized: yes"; then
                        sleep 2
                        /usr/bin/resolvectl dnssec "$1" "$global_mode" 2>/dev/null
                        break
                    fi
                    sleep 1
                    timeout=$((timeout - 1))
                done
            ) &
        fi
    fi
fi
