#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING. If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
#
#  file: /etc/X11/xinit/xinitrc
#  version: 1.3
#  coder: janui
#  date: December 2020
#
export XDG_CACHE_HOME="/tmp/.cache" &
export DISPLAY=":0" &

# start the touchscreen calibration utility
# needed for some screens (Pollin 7" tft)
# for this to work you have to disable loading luakit/chromium
#xinput_calibrator &

# set power management options
xset dpms 0 0 0 &

#turn screensaver off
xset s off &

# turn off screensaver
xset -dpms &

# start the window manager without titlebar and mouse
matchbox-window-manager -use_titlebar no -use_cursor no &

# install multimedia keyboard shortcuts
sudo -u http xbindkeys -f /srv/http/.xbindkeysrc -X :0 &

# use luakit as default
# luakit for local browser, compacter than chromium, supports JavaScript, which also scales <100%
sudo -u http /usr/bin/luakit

# optionally use chromium
# chromium will first need to be installed with the command: pacman -Sy chromium
# UI controls are already implemented
# the chromium configuration/parameter file for the user http is: /srv/http/.config/chromium-flags.conf
# sudo -u http /usr/bin/chromium http://localhost/
