#!/bin/bash
# File: /etc/X11/xinit/xinitrc
export XDG_CACHE_HOME="/tmp/.cache" &
export DISPLAY=":0" &

# start the touchscreen calibration utility
# needed for some screens (Pollin 7" tft)
# for this to work you have to disable loading midori/chromium
#xinput_calibrator &

# set power management options
xset dpms 0 0 0 &

#turn screensaver off
xset s off &

# turn off screensaver
xset -dpms &

# start the window manager without titlebar and mouse
matchbox-window-manager -use_titlebar no -use_cursor no &

# install multimedia keyboard shortcuts
sudo -u http xbindkeys -f /srv/http/.xbindkeysrc -X :0 &

# optional use of luakit for local browser which also scales <100%
#sudo -u http /usr/bin/luakit

# use chromium as default
# the chromium configuration/parameter file for the user http is: /srv/http/.config/chromium-flags.conf
sudo -u http /usr/bin/chromium http://localhost/
