# All options included directly in /etc/systemd/service/owntone.service
#[Service]
# always run as user mpd
#User = mpd
# give owntone 5 seconds to stop, otherwise timeout and kill
#TimeoutStopSec=5s
