#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING. If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
#
#  file: /usr/local/sbin/apt
#  version: 0.6
#  coder: janui
#  date: November 2023
#
# customisation of the apt command
# this script will automatically increase the size of the tmpfs /var/tmp to 100M before running the apt command
# this is only valid for RPiOS bookworm
os=$( redis-cli get os )
codename=$( redis-cli get codename )
if [ "$os" != "RPiOS" ] || [ "$codename" != "bookworm" ]; then
    # this file should not be there, remove it
    rm /usr/local/sbin/apt
else
    remounted=$( df -h | grep -i '/var/tmp' | grep -ic '100M' | xargs )
    if [ "$remounted" != "1" ] ; then
        # remount the tmpfs /var/tmp with 100M disk space
        mount -o remount,size=100M /var/tmp
    fi
fi
# now find the real apt command
paths=$( echo $PATH | sed 's/:/\n/g' )
for p in $paths ; do
    if [ "$p" == "/usr/local/sbin" ] ; then
        continue
    fi
    aptpath=$( find $p -maxdepth 1 -type f -name apt 2> /dev/null )
    if [ "$aptpath" != "" ] ; then
        aptcommand="$aptpath $@"
        break
    fi
done
if [ "$aptcommand" != "" ] ; then
    declare -i mem=$( redis-cli get memoryKb )
    if [ $mem -lt 600000 ] ; then
        redis-cli set mpd_playback_status stop
        mpc stop
        curl -s 'http://localhost/command/?switchplayer=MPD'
        systemctl stop rune_SY_wrk
        systemctl stop cmd_async_queue
        systemctl stop rune_PL_wrk
        systemctl stop rune_MPDEM_wrk
        systemctl stop spotifyd
        systemctl stop shairport_async
        systemctl stop rune_SSM_wrk
        systemctl stop rune_SDM_wrk
        systemctl stop mpd
        umount /srv/http/tmp/art
        redis-cli save
        sync
        echo 3 > /proc/sys/vm/drop_caches
        eval $aptcommand
        systemctl start mpd
        systemctl start cmd_async_queue
        systemctl start rune_SY_wrk
    else
        eval $aptcommand
    fi

else
    echo "apt: No such file or directory"
    exit 2
fi